[package]
name = "921starfish/unit"
description = "A minimal Unit type for Luau"
version = "0.9.4"
license = "MIT"
authors = ["YÅ«ya Hoshino <7694387+921starfish@users.noreply.github.com>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = ["src", "src/**", "default.project.json", "wally.toml", "LICENSE"]
private = false

[dependencies]

[server-dependencies]

[dev-dependencies]
