[package]
name = "921starfish/unit"
description = "A minimal Unit type for Luau"
version = "0.9.0"
license = "MIT"
authors = ["YÅ«ya Hoshino <hoshino_yuya@outlook.jp>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = ["src", "src/**", "wally.toml", "LICENSE"]
private = false

[dependencies]

[server-dependencies]

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"
